stage ('Clean workspace') {
  steps {
    cleanWs()
  }
}

stage ('Git Checkout') {
  steps {
      git branch: 'main', credentialsId: 'jenkins-github', url: 'https://github.com/janazi/TestSwaggerApi'
    }
  }

stage('Restore packages') {
  steps {
    bat "dotnet restore ${workspace}\\<path-to-solution>\\<solution-project-name>.sln"
  }
}